# Generated by Django 2.2.5 on 2019-09-11 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='remark_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date remarked'),
            preserve_default=False,
        ),
    ]
