# Generated by Django 2.2.5 on 2019-09-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletinBoard', '0003_auto_20190912_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='dete published'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='remark_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date remarked'),
        ),
    ]
